# Generated by Django 4.1.3 on 2022-12-04 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('building_name', models.CharField(max_length=50)),
                ('flat_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('password', models.BinaryField()),
                ('add_users', models.BooleanField()),
                ('give_access', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='glass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50)),
                ('glass_name', models.CharField(max_length=50)),
                ('glassSize1', models.CharField(max_length=50)),
                ('glassSize2', models.CharField(max_length=50)),
                ('polish', models.CharField(default=0, max_length=20)),
                ('client', models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.CASCADE, to='uttam_app.client_details')),
            ],
        ),
    ]
